- id: dune-format-dune-file
  name: dune-format-dune-file
  description: dune format-dune-file pre-commit hook for dune and dune-project files
  entry: pre-commit-dune-format-dune-file -i
  language: python
  types: [file]
  files: ^((?:[^/]+\/)*)(dune|dune-project|dune-workspace)$
  require_serial: false
  additional_dependencies: []
  minimum_pre_commit_version: 2.9.2
